language: erlang
otp_release:
  - 17.1
sudo: false
before_install:
  - wget http://s3.hex.pm/builds/elixir/master.zip
  - unzip -d elixir master.zip
before_script:
  - export PATH=`pwd`/elixir/bin:$PATH
  - yes | mix deps.get
  - mix deps.compile
  # Integration tests are not configured yet
  # - configuring virtualenv
  # - downloading python dependencies
  # - downloading jupyter_kernel_test application
  # - configuring kernel.json file with start_script.sh
script: mix test
