language: erlang
otp_release:
  - 17.1
sudo: false
before_install:
  - wget http://s3.hex.pm/builds/elixir/master.zip
  - unzip -d elixir master.zip
before_script:
  - export PATH=`pwd`/elixir/bin:$PATH
  - yes | mix deps.get
  - mix deps.compile
  - mix IElixir test_connection_file
script: mix test
