language: erlang
otp_release:
  - 17.1
sudo: false
before_install:
  - wget http://s3.hex.pm/builds/elixir/v1.0.3.zip
  - unzip -d elixir v1.0.3.zip
before_script:
  - export PATH=`pwd`/elixir/bin:$PATH
  - mix deps.get
  - mix deps.compile
script: mix test
